# Logstash deployment 생성 yaml 파일
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: default
spec:
  selector:
    matchLabels:
      app: logstash
  replicas: 1
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: cycloid87/jj-logstash:2.0     # 재중님 이미지로 로그스태시 설치
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5044
          protocol: TCP
        command: [ "sleep" ]
        args: [ "infinity" ]
