apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-app
  namespace: default
spec:
  selector:
    matchLabels:
      app: elastic-app
  replicas: 1
  template:
    metadata:
      labels:
        app: elastic-app
    spec:
      containers:
      - name: elastic
        image: cycloid87/jj-elasticsearch:2.0    # 재중님 이미지로 엘라스틱서치 설치
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9200
          protocol: TCP
        command: [ "sleep" ]
        args: [ "infinity" ]
