apiVersion: apps/v1
kind: Deployment
metadata:
  name: zeppelin
  namespace: default
spec:
  selector:
    matchLabels:
      app: zeppelin
  replicas: 1
  template:
    metadata:
      labels:
        app: zeppelin
    spec:
      containers:
      - name: zeppelin
        image: jerry2458/zeppelin:1.0  # 아직 안만들어진 이미지
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
          protocol: TCP
        command: [ "sleep" ]
        args: [ "infinity" ]
