apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: default
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: jerry2458/ubuntu-kafka:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9092
          protocol: TCP
        - containerPort: 9093
          protocol: TCP
        - containerPort: 2181
          protocol: TCP

        command: [ "sleep" ]
        args: [ "infinity" ]
